### ISSUE TITLE
AuthnRequest body via POST

### ISSUE THREAD

**Issue by dog5tar** [SAML-Toolkits/php-saml#264]
Hi all,

After short code review (lib/Saml2/AuthnRequest.php & lib/Saml2/Auth.php), it looks like php-saml does not support HTTP-POST for request being send from SP to IdP when SSO is initialised.

Is that correct or I'm missing something?

If HTTP-POST is not supported for initial request:

- shouldn't we be worrying that IdP might respond with "Error 413: Request Entity too large"?
- what about infosec implications sending request via GET?

A bit more insight is much appreciated!

**Comment by pitbulk** [comment]
HTTP-POST is not supported for AuthNRequest, LogoutRequest and LogoutResponse.

> shouldn't we be worrying that IdP might respond with "Error 413: Request Entity too large"?
Don't think so, you can always deflate the SAML message that will reduce the length.
Also take in mind that only the SSO SAMLResponse contains the SAML Assertion that is the element that can be very big.
If you review the XML template of AuthNRequest, LogoutRequest and LogoutResponse you will see that 
its length is small.

> what about infosec implications sending request via GET?
The data of those SAML messages is public (except the NameId that you can always encrypt).

That said, if you review [Conformance Requirements for the OASIS Security Assertion Markup Language (SAML) V2.0](http://docs.oasis-open.org/security/saml/v2.0/saml-conformance-2.0-os.pdf) Page 9, you will see that all IdPs MUST support the HTTP-Redirect binding, so you should experience any issue with IdPs that follows the SAML standard rules.

**Comment by mserious** [comment]
Thanks @pitbulk for the insights, much appreciated!

Is it safe to assume that all other requests except AuthNRequest, LogoutRequest and LogoutResponse are HTTP-POST bindings?

**Comment by pitbulk** [comment]
SP ACS URL uses HTTP-POST, other SAML exchange is expected to be HTTP-Redirect.

**Comment by FrittenKeeZ** [comment]
@pitbulk how big a task would it be to support HTTP-POST?
We're facing a requirement that we must also support HTTP-POST bindings for logout, so we will help sponsor this feature - I just don't quite know where to begin.

**Comment by pitbulk** [comment]
@FrittenKeeZ there is no interest in support that because that will increase the complexity of the toolkit (code and settings) and the main goal of the toolkit is to keep it simple.

If you require it in a project, you can use simpleSAMLphp which support any binding.

The task is big:
- Support send HTTP-POST binding for AuthNRequest, Logout Request and LogoutResponse
  including the signing process.
- Support receive HTTP-POST binding for Logout Request and LogoutResponse
  including validating sign.
- Extend toolkit to support the different bindings: Settings, Metadata, flows.

**Comment by FrittenKeeZ** [comment]
@pitbulk we only need to support receiving HTTP-POST binding for external IdP to log out of all services, so hopefully I can keep the complexity low enough to have it included into this project - maintaining backwards compatibility.

Regarding simpleSAMLphp it's just too big and is more of a framework than a utility as I see it - also I have absolutely no idea where to start with it, since the naming differs so much from anything else I work with.

**Comment by FrittenKeeZ** [comment]
@pitbulk sorry for all this spamming, but I got it all wrong.
We don't need to support `HTTP-POST` bindings at all, but we need to handle external logout requests through `HTTP-REDIRECT`:
- `SAMLRequest`
- `SigAlg`
- `Signature`
I guess it's still a matter of constructing a `SAMLResponse` for them to process.

**Comment by dsantuc** [comment]
@pitbulk  I'm implementing a SAML SP SSO integration for the first time and was also wondering if the IdP could require me to submit the AuthNRequest using the HTTP-POST binding, so it's good to know that the spec requires IdPs to support the redirect binding for this request.

That said, it seems from reviewing the code, that you _could_ do it if necessary by doing something like this:

```
<?php
use \OneLogin\Saml2\AuthnRequest,
use \OneLogin\Saml2\Settings;

$settings = new Settings();
$idpSettings = $settings->getIdPData();
$endpoint = $idpSettings['singleSignOnService']['url'];
$request = new AuthnRequest($settings);
$payload = base64_encode($request->getXML());
$redirect = "/dashboard";
?>

<html>
<body onload="document.forms[0].submit()">
<form action="<?php echo $endpoint; ?>" method="POST">
<input type="hidden" name="SAMLRequest" value="<?php echo $payload; ?>" />
<input type="hidden" name="RelayState" value="<?php echo $redirect; ?>" />

<!-- maybe other parameters for the signature, if required? -->

<input type="submit" value="Log me in!" />
</form>
</body>
</html>
```

(This is assuming the IdP doesn't require a signed request.)

Would that work?

**Comment by pitbulk** [comment]
that will work if the IdP does not reqire signed AuthNRequests.
