### ISSUE TITLE
Stop supporting EOL php 5

### ISSUE THREAD

**Issue by Hikariii** [SAML-Toolkits/php-saml#364]
Relating to an older issue of me https://github.com/onelogin/php-saml/issues/59 I suggest to simplify different branches and move to php 7 for the master branch.
Php5 is EOL and will not even receive security patches anymore.

http://php.net/supported-versions.php

**Comment by pitbulk** [comment]
Is true that PHP5.6 is not supported anymore, but there are tons of apps working with PHP5.X and not with PHP7.X.

That why I plan to maintain supporting PHP5.6 here.

I think point master to 3.X branch rather than 2.X is something that must be done, but not an imminent change because there are tons of integrations that could be pointing to master, expecting it 2.X and a change can break their environments.
