### ISSUE TITLE
index=1 is hardcoded in lib/saml2/Metadata.php on AssertionConsumerService element

### ISSUE THREAD

**Issue by prashantb22** [SAML-Toolkits/php-saml#444]
I am using the php-saml library and implemented the service provider part. 
I generate metadata using the library. 

In Metadata.php inside builder function index attribute is set to 1 for AssertionConsumerService and AttributeConsumingService XML elements. 

I have below questions
1. why it is directly set to 1.
2. Is it ok if I changed the value to 0. What will be the impact? Are we using this index="1" value anywhere in code.

When I try to configure generate metadata in IDP it gives me below error.

`SEVERE - /EntitiesDescriptor/EntityDescriptor/SPSSODescriptor/AssertionConsumerService/@index           AssertionConsumerService index should be 0`

Please suggest what is the impact if I changed the value from 1 to 0.

**Comment by pitbulk** [comment]
I believe I used as template the one defined here which contains index=1 for AssertionConsumerService and AttributeConsumingService:
http://www.datypic.com/sc/saml2/e-md_SPSSODescriptor.html

If you check the wikipedia, the SP metadata also contains a AssertionConsumerService with index=1
https://en.wikipedia.org/wiki/SAML_2.0#Service_provider_metadata

Not sure of the impact of modifying it to be 0 instead of 1.

What IdP are you using that validates that the index may be 0?
