### ISSUE TITLE
Read cert from idp metadata file

### ISSUE THREAD

**Issue by brosua** [SAML-Toolkits/php-saml#524]
Hi,

is it possible to read the idp X509cert from the metadata file? 
If no x509cert is added to the php-saml config file, an exception is thrown.

**Comment by pitbulk** [comment]
The extension includes a [IdP Metadata file parser](https://github.com/SAML-Toolkits/php-saml/blob/4.x-dev/src/Saml2/IdPMetadataParser.php) that you can use in order to obtain the IdP data, to be injected to the SAML Settings of the toolkit. Such parser support the x509cert as well.

So you basically will be able to dynamically parse IdP data, extract the info, generate the settings dynamically and then build with that your Auth and Settings objects.
